### ISSUE TITLE
[PE-D][Tester C] There is no sample data when the .jar file is first opened.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14a-4/tp#328] opened 2024-11-08 18:08 UTC
Steps to reproduce error:
1. Download the .jar file into an empty folder.
2. Run the .jar 

Expected Output: Contains sample data as shown in the UG.

![sampledatainUG.png](https://raw.githubusercontent.com/XinghuaJulia/ped/main/files/92520639-64e6-48ce-9fff-b38126f24f61.png)

Actual Output: Contains no sample data at all.

![emptylistbug.png](https://raw.githubusercontent.com/XinghuaJulia/ped/main/files/52f5fdfc-10ee-4e3e-8346-5ced8a351dcf.png)

The UG seems to promise users some sample data but perhaps due to some slight issues, there is no sample data. This is medium severity as it may dissuade some users from using the application as there is a perceived barrier of entry.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: XinghuaJulia/ped#9

**Comment by KrashKart** [comment] 2024-11-08 18:12
Closed, duplicate of #312

**Closed by KrashKart** 2024-11-08 18:12 UTC
