### ISSUE TITLE
[PE-D][Tester A] Duplicate Handling: Does not allow contacts with the same name

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14a-4/tp#303] opened 2024-11-08 16:17 UTC
![Screenshot 2024-11-08 at 4.26.13 PM.png](https://raw.githubusercontent.com/ChinSekYi/ped/main/files/64ce3d75-c285-43ae-a2d9-5311e5c46e42.png)

App should account for contacts with the same name because it is very likely that multiple NUS students have the same name. 
For example, common names in NUS are:
- Jun Jie
- Xin yi 
- Charmaine
- Nyugen 

Duplicate handling should be done for phone numbers and emails only. 

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: ChinSekYi/ped#5

**Comment by KrashKart** [comment] 2024-11-08 17:57
Closed, duplicate of #289

**Closed by KrashKart** 2024-11-08 17:57 UTC
